// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SigortaTakipSistemi.Data;

#nullable disable

namespace SigortaTakipSistemi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250809110607_AddPoliceTuruSirket")]
    partial class AddPoliceTuruSirket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SigortaTakipSistemi.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsimSoyisim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("SigortaTakipSistemi.Models.Police", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Kisi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<string>("PoliceNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PoliceSuresi")
                        .HasColumnType("int");

                    b.Property<int>("PoliceTuruId")
                        .HasColumnType("int");

                    b.Property<int>("SigortaSirketiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TanzimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("TcNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TelefonNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.HasIndex("PoliceTuruId");

                    b.HasIndex("SigortaSirketiId");

                    b.ToTable("Policeler");
                });

            modelBuilder.Entity("SigortaTakipSistemi.Models.PoliceTuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AcentaPrimi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prim")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PoliceTurleri");
                });

            modelBuilder.Entity("SigortaTakipSistemi.Models.PoliceTuruSirket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AcentaPrimiYuzde")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("PoliceTuruId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrimYuzde")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SigortaSirketiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoliceTuruId");

                    b.HasIndex("SigortaSirketiId", "PoliceTuruId")
                        .IsUnique();

                    b.ToTable("PoliceTuruSirketler");
                });

            modelBuilder.Entity("SigortaTakipSistemi.Models.SigortaSirketi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SigortaSirketleri");
                });

            modelBuilder.Entity("SigortaTakipSistemi.Models.Police", b =>
                {
                    b.HasOne("SigortaTakipSistemi.Models.Kullanici", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SigortaTakipSistemi.Models.PoliceTuru", "PoliceTuru")
                        .WithMany()
                        .HasForeignKey("PoliceTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SigortaTakipSistemi.Models.SigortaSirketi", "SigortaSirketi")
                        .WithMany()
                        .HasForeignKey("SigortaSirketiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("PoliceTuru");

                    b.Navigation("SigortaSirketi");
                });

            modelBuilder.Entity("SigortaTakipSistemi.Models.PoliceTuruSirket", b =>
                {
                    b.HasOne("SigortaTakipSistemi.Models.PoliceTuru", "PoliceTuru")
                        .WithMany()
                        .HasForeignKey("PoliceTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SigortaTakipSistemi.Models.SigortaSirketi", "SigortaSirketi")
                        .WithMany()
                        .HasForeignKey("SigortaSirketiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PoliceTuru");

                    b.Navigation("SigortaSirketi");
                });
#pragma warning restore 612, 618
        }
    }
}
